version: '2'
services:
  fpm:
    build: php7fpm
    restart: always
    volumes:
      - ./wordpress.matbra.com/:/var/www/wordpress.matbra.com
      - ./php7fpm/sendmail.mc:/usr/share/sendmail/cf/debian/sendmail.mc
      - ./php7fpm/gmail-auth.db:/etc/mail/authinfo/gmail-auth.db
      - ./logs/sendmail/:/var/log/sendmail
    links:
      - mariadb 
    hostname: boarders.com.br
    networks:
      - backend
  
  nginx:
    image: nginx:1.10.1-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.vhost:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./wordpress.matbra.com/:/var/www/wordpress.matbra.com
      - ./jekyll.matbra.com/:/var/www/jekyll.matbra.com
    links:
      - fpm
    networks:
      - zotabox
      - backend
    environment:
        - VIRTUAL_HOST=wordpress.matbra.com
        
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=
    volumes:
    -   ./data/db:/var/lib/mysql
    networks:
      - backend
      
  wpcli:
    image: wordpress:cli
    volumes:
      - ./wordpress.matbra.com/:/var/www/html
      - ./backups:/var/www/backups
    links:
      - mariadb
    #entrypoint: wp  
    #command: "--info"
    networks:
      - backend
    
networks:
  zotabox:
    external: true
  backend:
    driver: bridge  
